### ISSUE TITLE
What is `python-docker` used for in the role?

### ISSUE THREAD

**Issue by andmos** [zaxos/docker-ce-ansible-role#1]
Just out of curiosity, what is `python-docker` used for in the role on RHEL? 
It seems like it is interfering with some other Python packages I use on my build servers that is containing Ansible as well as Docker, so I try to figure out what is what here 😆

**Comment by zaxos** [comment]
Hello!
The reason I included `python-docker` package is because `docker-py` (`python-docker` or `python-docker-py` pkg on CentOS) is a requirement for `docker_container` ansible module (http://docs.ansible.com/ansible/latest/docker_container_module.html) and other docker related ansible modules.
I thought that, like myself, the majority of people using this role will also use those ansible modules.
Also, I have never tested this role on RHEL since Docker CE isn’t supported on RHEL, only Docker EE is.

**Comment by andmos** [comment]
All right! Thanks for the feedback, it makes totally sense 👍 I can also confirm that it works on CentOS at least.
